global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "chat_service_api"
    static_configs:
      - targets: ["backend:9000"]

  - job_name: "chat_service_metrics"
    static_configs:
      - targets: ["backend:9001"]